// updater.js — thin wrapper around electron-updater's `autoUpdater`. Manual,
// user-triggered check/download/install only (`autoDownload`/
// `autoInstallOnAppQuit` are both off) — nothing downloads or installs
// itself without a click, matching the rest of this app's "nothing runs
// unless you tell it to" stance (see the dangerous-command-guard note at
// the top of CLAUDE.md — same philosophy, different feature).
//
// Update feed is GitHub Releases on this repo (see `build.publish` in
// package.json) — `electron-builder --win --publish always` (the `release`
// npm script) is what actually creates a release and uploads the NSIS
// installer + latest.yml there; this module only ever reads from it.
//
// Every state change is pushed to the renderer over one 'update-status'
// channel rather than being returned from the ipc.js handlers directly,
// because electron-updater's own API is event-driven (a check/download call
// resolves near-instantly; the real result — available/not-available/
// progress/downloaded/error — arrives later via events). ipc.js's handlers
// just kick off the corresponding call and let these events carry the result.
'use strict';

const { app } = require('electron');
const { autoUpdater } = require('electron-updater');
const { getMainWindow } = require('./window');

function send(status, extra = {}) {
  const win = getMainWindow();
  if (win && !win.isDestroyed()) {
    win.webContents.send('update-status', { status, ...extra });
  }
}

let initialized = false;

/** Wires autoUpdater's events to the renderer. Call once at startup. */
function initUpdater() {
  if (initialized) return;
  initialized = true;

  autoUpdater.autoDownload = false;
  autoUpdater.autoInstallOnAppQuit = false;

  autoUpdater.on('checking-for-update', () => send('checking'));
  autoUpdater.on('update-available', (info) => send('available', { version: info.version }));
  autoUpdater.on('update-not-available', () => send('not-available'));
  autoUpdater.on('download-progress', (progress) => send('downloading', { percent: Math.round(progress.percent) }));
  autoUpdater.on('update-downloaded', (info) => send('downloaded', { version: info.version }));
  autoUpdater.on('error', (err) => send('error', { message: String((err && err.message) || err) }));
}

/**
 * Running via `npm start` (electron .) has no app-update.yml — that file is
 * generated by electron-builder into the packaged app's resources, pointing
 * at the publish config, and only exists once the app is actually built/
 * installed. Calling checkForUpdates() without it throws, so this is
 * checked up front rather than surfaced as a confusing error from deep
 * inside electron-updater.
 */
function checkForUpdates() {
  if (!app.isPackaged) {
    send('unsupported', { message: 'Updates only work in the installed app, not when running from source (npm start).' });
    return;
  }
  autoUpdater.checkForUpdates().catch((err) => send('error', { message: String(err.message || err) }));
}

function downloadUpdate() {
  autoUpdater.downloadUpdate().catch((err) => send('error', { message: String(err.message || err) }));
}

/** Quits and installs the already-downloaded update, then relaunches. */
function quitAndInstall() {
  // Explicit, not relying on the 'before-quit' listener in index.js to beat
  // the window's 'close' handler to it — see tray.js's Quit item for the
  // same defensive pattern; without this the window would just hide (per
  // window.js's close handler) instead of letting the app actually quit.
  app.isQuitting = true;
  autoUpdater.quitAndInstall();
}

module.exports = { initUpdater, checkForUpdates, downloadUpdate, quitAndInstall };
